spring:
  application:
    name: stock-service

  datasource:
    url: jdbc:postgresql://localhost:5433/shopflow_stock
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: stock-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.shopflow.commons.events"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  jms:
    pub-sub-domain: false

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health, info